import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { McpState } from '../src/client/mcpState.js'

/** @author ddj 2026年10月08号 @returns Controllable promise for race tests. */
function deferred<T>() {
  let resolve!: (value: T) => void
  let reject!: (error: unknown) => void
  const promise = new Promise<T>((ok, fail) => { resolve = ok; reject = fail })
  return { promise, resolve, reject }
}
const initial = { ok: true, servers: [], projects: [] }
/** @author ddj 2026年10月08号 @returns A deterministic controller and transport. */
function setup() {
  const request = vi.fn(async () => initial)
  const changed = vi.fn()
  const state = new McpState(request as any, changed, { interval: 100, timeout: 50 })
  return { state, request, changed }
}

describe('MCP state controller', () => {
  beforeEach(() => vi.useFakeTimers())
  afterEach(() => vi.useRealTimers())
  it('initial load keeps list/projects; inactive tabs never poll', async () => {
    const { state, request } = setup()
    await state.load()
    expect(request.mock.calls.map((call) => call[0])).toEqual(['mcp.list', 'mcp.projects'])
    await vi.advanceTimersByTimeAsync(1000)
    expect(request).toHaveBeenCalledTimes(2)
    state.dispose()
  })
  it('polls only snapshot while active and visible and resumes after visibility', async () => {
    const { state, request } = setup()
    await state.load()
    state.setActive(true)
    await vi.advanceTimersByTimeAsync(100)
    expect(request.mock.calls.at(-1)?.[0]).toBe('mcp.snapshot')
    state.setVisible(false)
    const count = request.mock.calls.length
    await vi.advanceTimersByTimeAsync(1000)
    expect(request).toHaveBeenCalledTimes(count)
    state.setVisible(true)
    await vi.advanceTimersByTimeAsync(100)
    expect(request).toHaveBeenCalledTimes(count + 1)
    expect(request.mock.calls.filter((call) => call[0] === 'mcp.projects')).toHaveLength(1)
    state.dispose()
  })
  it('has no overlapping reads even when transport ignores abort', async () => {
    const { state, request } = setup()
    await state.load()
    const pending = deferred<any>()
    request.mockImplementation(() => pending.promise)
    state.setActive(true)
    await vi.advanceTimersByTimeAsync(100)
    const signal = request.mock.calls.at(-1)?.[2] as AbortSignal
    await vi.advanceTimersByTimeAsync(1000)
    expect(signal.aborted).toBe(true)
    expect(request).toHaveBeenCalledTimes(3)
    pending.resolve(initial)
    await vi.advanceTimersByTimeAsync(100)
    expect(request).toHaveBeenCalledTimes(4)
    state.dispose()
  })
  it('invalidates pending snapshot on tab leave and ignores late result', async () => {
    const { state, request } = setup()
    await state.load()
    const pending = deferred<any>()
    request.mockImplementation(() => pending.promise)
    state.setActive(true)
    await vi.advanceTimersByTimeAsync(100)
    state.setActive(false)
    pending.resolve({ ...initial, servers: [{ id: 'stale' }] })
    await vi.advanceTimersByTimeAsync(1000)
    expect(state.view.servers).toEqual([])
    expect(request).toHaveBeenCalledTimes(3)
    state.dispose()
  })
  it('locks all mutations synchronously and suppresses older snapshots', async () => {
    const { state, request } = setup()
    await state.load()
    const snapshot = deferred<any>()
    request.mockImplementation(() => snapshot.promise)
    state.setActive(true)
    await vi.advanceTimersByTimeAsync(100)
    const mutation = deferred<any>()
    const task = vi.fn(() => mutation.promise)
    const patch = vi.fn(() => { state.view.servers = [{ id: 'new' }] as any })
    const first = state.mutate('save', task, patch)
    expect(state.view.busy).toBe('save')
    expect(await state.mutate('toggle', task, patch)).toBe(false)
    expect(task).toHaveBeenCalledTimes(1)
    mutation.resolve({ ok: true })
    expect(await first).toBe(true)
    snapshot.resolve({ ...initial, servers: [{ id: 'old' }] })
    await vi.advanceTimersByTimeAsync(0)
    expect(state.view.servers[0]?.id).toBe('new')
    expect(state.view.busy).toBe('')
    state.dispose()
  })
  it('catches synchronous config errors and RPC failures without calling success', async () => {
    const { state } = setup()
    const patch = vi.fn()
    expect(await state.mutate('save', () => { throw new Error('bad headers') }, patch)).toBe(false)
    expect(state.view.error).toContain('bad headers')
    expect(state.view.busy).toBe('')
    expect(await state.mutate('project-save', async () => ({ ok: false, error: 'disk denied' }), patch)).toBe(false)
    expect(state.view.error).toContain('disk denied')
    expect(patch).not.toHaveBeenCalled()
    state.dispose()
  })
  it('ignores initial and mutation results after dispose and cleans timers', async () => {
    const { state, request, changed } = setup()
    const pending = deferred<any>()
    request.mockImplementation(() => pending.promise)
    const load = state.load()
    state.dispose()
    const count = changed.mock.calls.length
    pending.resolve({ ...initial, servers: [{ id: 'late' }] })
    await load
    await vi.advanceTimersByTimeAsync(1000)
    expect(changed).toHaveBeenCalledTimes(count)
    expect(state.view.servers).toEqual([])
    expect(vi.getTimerCount()).toBe(0)
    const patch = vi.fn()
    expect(await state.mutate('save', async () => ({ ok: true }), patch)).toBe(false)
    expect(patch).not.toHaveBeenCalled()
  })
  it('does not commit mutation success after unmount', async () => {
    const { state } = setup()
    const pending = deferred<any>()
    const patch = vi.fn()
    const mutation = state.mutate('save', () => pending.promise, patch)
    state.dispose()
    pending.resolve({ ok: true })
    expect(await mutation).toBe(false)
    expect(patch).not.toHaveBeenCalled()
  })
  it('waits for both initial reads to settle after one fails, preventing overlap', async () => {
    const { state, request } = setup()
    const projects = deferred<any>()
    request.mockImplementation((method: string) => method === 'mcp.list' ? Promise.reject(new Error('list failed')) : projects.promise)
    const load = state.load()
    state.setActive(true)
    await vi.advanceTimersByTimeAsync(1000)
    expect(request).toHaveBeenCalledTimes(2)
    projects.resolve(initial)
    await load
    await vi.advanceTimersByTimeAsync(100)
    expect(request.mock.calls.at(-1)?.[0]).toBe('mcp.snapshot')
    state.dispose()
  })
  it('does not let a late initial load replace committed mutation data', async () => {
    const { state, request } = setup()
    const pending = deferred<any>()
    request.mockImplementation(() => pending.promise)
    const load = state.load()
    await state.mutate('save', async () => ({ ok: true }), () => { state.view.servers = [{ id: 'new' }] as any })
    pending.resolve({ ...initial, servers: [{ id: 'old' }] })
    await load
    expect(state.view.servers[0]?.id).toBe('new')
    state.dispose()
  })
  it('invalidates a hidden-document response and resumes with a fresh snapshot', async () => {
    const { state, request } = setup()
    await state.load()
    const pending = deferred<any>()
    request.mockImplementationOnce(() => pending.promise)
    state.setActive(true)
    await vi.advanceTimersByTimeAsync(100)
    state.setVisible(false)
    pending.resolve({ ...initial, servers: [{ id: 'hidden' }] })
    await vi.advanceTimersByTimeAsync(0)
    expect(state.view.servers).toEqual([])
    state.setVisible(true)
    await vi.advanceTimersByTimeAsync(100)
    expect(request).toHaveBeenCalledTimes(4)
    state.dispose()
  })
  it('resumes snapshot polling after rejected read', async () => {
    const { state, request } = setup()
    await state.load()
    request.mockRejectedValueOnce(new Error('network'))
    state.setActive(true)
    await vi.advanceTimersByTimeAsync(100)
    expect(state.view.error).toContain('network')
    await vi.advanceTimersByTimeAsync(100)
    expect(request).toHaveBeenCalledTimes(4)
    expect(state.view.error).toBe('')
    state.dispose()
  })
})
